# action.yml
name: 'Add-header'
description: 'Add a header to any file within you repo.'

# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding
branding:
  icon: 'align-left'
  color: 'red'

inputs:
  dry-run:
    description: 'Do not actually make changes, instead effected files are viewable in the logs'
    required: false
    default: "false"
  verbose:
    description: 'Add more output to the console for debugging'
    required: false
    default: "false"

outputs:
  time: # id of output
    description: 'The time we greeted you'

runs:
  using: 'docker'
  image: 'Dockerfile'
  # Args must be passed on individual lines "--dry-run ${{ inputs.dry-run }}" would be invalid
  args:
    - --dry-run
    - ${{ inputs.dry-run }}
    - --verbose
    - ${{ inputs.verbose }}

