name: Python Lint & Test

on:
  workflow_dispatch: # Allow manually running
  workflow_call: # Allow another workflow to call this one
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
  push:
    branches:
      - main

jobs:
  build:
    name: Python lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
      
    - name: Install dependencies
      run: python3 -m pip install -r requirements.txt

    - name: Black formatter check
      run: python3 -m black --line-length 120 --check --verbose app
    
    - name: Run Pytest
      run: python3 -m pytest --cov app --cov-report html --cov-report term --cov-report xml
    
    - name: Upload reports to Codecov
      uses: codecov/codecov-action@v4-beta
      env: 
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }} # Required for v4
      with:
        fail_ci_if_error: true
        files: coverage.xml