name: Python Lint & Test

on:
  workflow_dispatch: # Allow manually running
  # push:
  #   branches:
  #     - main

jobs:
  build:
    name: Python lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
      
    - name: Install dependencies
      run: |
        python3 -m pip install -r requirements.txt
      # python -m pip install --upgrade pip

    - name: Black formatter check
      run: black --line-length 120 --check --verbose app

    - name: Run Pytest
      run: python3 -m pytest --cov app
